# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# App defs

def network
  pod 'Alamofire'
  pod 'SwiftyJSON'
end

# App targets

target 'Liberty_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  network

end

target 'Liberty_macOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  network

end

target 'VPN WidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VPN WidgetExtension

end

target 'WireGuard Network Extension iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WireGuard Network Extension iOS

end

target 'WireGuard Network Extension macOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WireGuard Network Extension iOS

end

